esphome:
  name: ttgo-t-display
  includes:
    - esphomeRemote/ttgo-t-display-drawmenu.h
    - esphomeRemote/ttgo-t-display.h
  platformio_options:
    build_flags:
      - -std=gnu++17
    build_unflags:
      - -std=gnu++11

esp32:
  board: featheresp32
  framework:
    type: arduino
    version: dev
    platform_version: 5.2.0

packages:
  extraconfig: !include esphomeRemote/extraconfig.yaml
  myconfig: !include esphomeRemote/myconfig.yaml

# Enable logging
logger:

# Enable Home Assistant API
api:
  id: homeassistantapi

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ttgo-T-Display Fallback Hotspot"
    password: "5Z0OeWeAO03V"

captive_portal:
    
spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19

substitutions:
  large_font_size: "24"
  medium_font_size: "15"
  small_font_size: "14"
  icon_size: "18"
  icon_size_large: "19"
  header_height: "16"
  margin_size: "4"
  scroll_bar_width: "6"
  bottom_bar_margin: "1"
  color_accent_primary_red: 0%
  color_accent_primary_green: 45%
  color_accent_primary_blue: 68%
  display_timeout: "10000"
  sleep_after: "7200"
  menu_rollover_on: "true"
  dark_mode: "true"

globals:
  - id: menuIndex
    type: int

  - id: currentMenuSize
    type: int
    
#interval:
#  - interval: 1s
#    then:
#    - lambda: |-
#        idleTick();
#  - interval: 0.3s
#    then:
#    - lambda: |-
#        activeTick();

deep_sleep:
  id: deep_sleep_1

#binary_sensor:
#  - platform: status
#    name: "${boot_name} Node Status"
#    id: system_status

time:
  - platform: homeassistant
    id: esptime

switch:
  - platform: template
    name: Sleep Toggle
    id: sleep_toggle
    optimistic: true
    on_turn_on:
      then:
        - deep_sleep.enter:
            id: deep_sleep_1
  - platform: gpio
    pin:
      number: 27
      inverted: false
    id: comb
    internal: true
  - platform: gpio
    pin:
      number: 26
      inverted: false
    id: coma
    internal: true
  - platform: gpio
    pin: GPIO4
    name: "Backlight"
    id: backlight
    internal: true
    restore_mode: ALWAYS_ON

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
      mode:
        input: true
        pullup: true
    name: "T-Display Button Input 0"
    id: tdisplay_button_input_0
    internal: true
    on_press:
      then:
        - script.execute: nextMenuItem    
  - platform: gpio
    pin:
      number: GPIO35
      inverted: true
    name: "T-Display Button Input 1"
    id: tdisplay_button_input_1
    internal: true
    on_press:
      then:
      - lambda: |-
          ESP_LOGD("buttonpress1", "pressed");
      - script.execute: buttonSelect

display:
  - platform: st7789v
    model: TTGO TDisplay 135x240
    id: my_display
    backlight_pin: GPIO4
    cs_pin: GPIO5
    dc_pin: GPIO16
    reset_pin: GPIO23
    rotation: 90°
#   auto_clear_enabled: True
#   update_interval: 5s
    pages:
      - id: page0
        lambda: |-        
          drawMyMenu(id(mainmenu));          
      - id: page1
        lambda: |-
          drawMyMenu(id(lightsoffmenu));
      - id: page2
        lambda: |-
          drawMyMenu(id(lightsonmenu));
      - id: page3
        lambda: |-
          drawMyMenu(id(dummymenu));          

