color:
  - id: my_red
    red: 100%
    green: 0%
    blue: 0%
  - id: my_yellow
    red: 100%
    green: 75%
    blue: 10%
  - id: my_green
    red: 0%
    green: 100%
    blue: 0%
  - id: color_accent_primary
    red: ${color_accent_primary_red}
    green: ${color_accent_primary_green}
    blue: ${color_accent_primary_blue}
  - id: my_gray_dark
    red: 40%
    green: 40%
    blue: 40%
  - id: my_gray_dark_2
    red: 8%
    green: 8%
    blue: 8%
  - id: my_gray
    red: 10%
    green: 10%
    blue: 10%
  - id: my_black
    red: 0%
    green: 0%
    blue: 0%
  - id: my_white
    red: 100%
    green: 100%
    blue: 100%

font:
## Font needs to be monospace!
  - file: "fonts/iosevka.ttf"
    id: large_font
    size: ${large_font_size}
    glyphs: '*/\$#<>!?"%()[]+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz&êÊîÎâÂôÔéÉíÍáÁóÓëËüÜïÏṣṢ''’'
  - file: "fonts/iosevka.ttf"
    id: medium_font
    size: ${medium_font_size}
    glyphs: '*/\$#<>!?"%()[]+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz&êÊîÎâÂôÔéÉíÍáÁóÓëËüÜïÏṣṢ''’'
  - file: "fonts/iosevka.ttf"
    id: small_font
    size: ${small_font_size}
    glyphs: '*/\$#<>!?"%()[]+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz&êÊîÎâÂôÔéÉíÍáÁóÓëËüÜïÏṣṢ''’'
  - file: 'fonts/materialdesignicons-webfont.ttf' 
    id: material_font_large
    size: ${icon_size_large}
    glyphs: [
      '󰐊', # mdi-play
      '󰓛', # mdi-stop
      '󰏤', # home-pause
      '󰽥', # mdi-moon-waning-crescent
      '󰒝', # mdi-shuffle
      '󰒞', # mdi-shuffle-disabled
      '󰕾', # mdi-volume-high
      '󰕿', # mdi-volume-low
      '󰚺', # mdi-plex
      '󰝆', # mdi-netflix
      '󰗃', # mdi-youtube
      '󰓇', # mdi-spotify
      '󰔂', # mdi-television
    ]  
  - file: 'fonts/materialdesignicons-webfont.ttf' 
    id: material_font_small
    size: ${icon_size}
    glyphs: [
      '󰐊', # mdi-play
      '󰓛', # mdi-stop
      '󰏤', # home-pause
      '󰽥', # mdi-moon-waning-crescent
      '󰒝', # mdi-shuffle
      '󰒞', # mdi-shuffle-disabled
      '󰕾', # mdi-volume-high
      '󰕿', # mdi-volume-low
      '󰚺', # mdi-plex
      '󰝆', # mdi-netflix
      '󰗃', # mdi-youtube
      '󰓇', # mdi-spotify
      '󰔂', # mdi-television
    ]

globals:
## Size of the large font above
  - id: large_font_size
    type: int
    restore_value: no
    initial_value: ${large_font_size}
    
## Size of the medium font above
  - id: medium_font_size
    type: int
    restore_value: no
    initial_value: ${medium_font_size}
    
## Size of the small font above
  - id: small_font_size
    type: int
    restore_value: no
    initial_value: ${small_font_size}
    
## Height / width ratio of the monospace font used
  - id: font_size_width_ratio
    type: double
    restore_value: no
    initial_value: "0.6"
    
## Status bar height
  - id: header_height
    type: int
    restore_value: no
    initial_value: ${header_height}
    
## Global margin size
  - id: margin_size
    type: int
    restore_value: no
    initial_value: ${margin_size}
    
## Scrollbar total width
  - id: scroll_bar_width
    type: int
    restore_value: no
    initial_value: ${scroll_bar_width}
    
## Volume bar and media duration bar margin
  - id: bottom_bar_margin
    type: int
    restore_value: no
    initial_value: ${bottom_bar_margin}
    
## Height and width of the icons used in px
  - id: icon_size
    type: int
    restore_value: no
    initial_value: ${icon_size}
    
## Height and width of the icons used in px
  - id: icon_size_large
    type: int
    restore_value: no
    initial_value: ${icon_size_large}
    
## Turn off display after x seconds of idle
  - id: display_timeout
    type: int
    restore_value: no
    initial_value: ${display_timeout}

## Go to sleep after x seconds of idle
  - id: sleep_after
    type: int
    restore_value: no
    initial_value: ${sleep_after}

## Let the menu selection roll-over when reaching the beginning/end
  - id: menu_rollover_on
    type: bool
    restore_value: no
    initial_value: ${menu_rollover_on}

## Black background
  - id: dark_mode
    type: bool
    restore_value: no
    initial_value: ${dark_mode}
    

